spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thiet_bi_truong_dh_utc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      pool-name: TestHikariCP

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect # CH? DÒNG NÀY LÀ ?ÚNG!
    hibernate:
      ddl-auto: update                                   # ho?c validate n?u không mu?n t? t?o b?ng
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080